# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: windows-latest

stages:
- stage: Tests
  jobs:
  - job: Build_And_Test
    steps:

    - task: DotNetCoreCLI@2
      displayName: 'Restore packages for Domain tests'
      inputs:
        command: 'restore'
        projects: '**/Domain.Tests.csproj'
        feedsToUse: 'select'
        
    - task: DotNetCoreCLI@2
      displayName: 'Run Domain tests'
      inputs:
        command: 'test'
        projects: '**/Domain.Tests.csproj'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      displayName: 'Restore packages for WebAPI tests'
      inputs:
        command: 'restore'
        projects: '**/WebApi.Tests.csproj'
        feedsToUse: 'select'
        
    - task: DotNetCoreCLI@2
      displayName: 'Run WebAPI tests'
      inputs:
        command: 'test'
        projects: '**/WebApi.Tests.csproj'
        feedsToUse: 'select'