# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Unit tests build'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore packages for Domain unit tests'
  inputs:
    command: 'restore'
    projects: '**/Domain.UnitTests.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Run Domain unit tests'
  inputs:
    command: 'test'
    projects: '**/Domain.UnitTests.csproj'
    feedsToUse: 'select'