# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: windows-latest

stages:
- stage: Build
  jobs:
  - job: Build_And_Test
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore packages for Domain module'
      inputs:
        command: 'restore'
        projects: '**/Domain.csproj'
        feedsToUse: 'select'
        
    - task: DotNetCoreCLI@2
      displayName: 'Build Domain module'
      inputs:
        command: 'build'
        projects: '**/Domain.csproj'
        
    - task: DotNetCoreCLI@2
      displayName: 'Restore packages for Domain unit tests'
      inputs:
        command: 'restore'
        projects: '**/Domain.UnitTests.csproj'
        feedsToUse: 'select'
        
    - task: DotNetCoreCLI@2
      displayName: 'Run Domain unit tests'
      inputs:
        command: 'test'
        projects: '**/Domain.UnitTests.csproj'
        feedsToUse: 'select'

#    - task: VSTest@2
#      inputs:
#        testSelector: 'testAssemblies'
#        testAssemblyVer2: |
#          **\Domain.UnitTests.dll
#          !**\*TestAdapter.dll
#          !**\obj\**
#          !**\bin\**\ref\**
#        searchFolder: '$(System.DefaultWorkingDirectory)'